# User config
author: "parf"
tagline: "some projects in data science and creative coding"
description: "I lead a team of data scientists @Google. In my spare time I dabble in creative coding and other data-related explorations."
keywords: "data science, data visualization, creative coding, generative art"
# email: "pineapple@example.com"
linkedin: "https://uk.linkedin.com/in/lauraparfitt"
# twitter: "https://twitter.com/"
github: "https://github.com/Parfy"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
